---
title: "trike_graphs"
author: "Maria Godinez"
date: "February 1, 2022"
output: word_document
---


```{r include=FALSE}
library(ggthemes)
library(ggplot2)
library(dplyr)
library(readxl)
NK <- read_excel("Excel for GTB graphs 10-20-21.xlsx")

```


```{r include=FALSE}
tike_data <- read_excel("TriKE Cytotox Data Summary 7-29-21.xlsx", 
    sheet = "All Patient Data Summary")
```



## HL60 E:T 20:1

```{r include=FALSE}
HL60_20<-subset(tike_data, Analyte=="I20/HL60 E:T 20:1" & (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_20$AnalysisResultFormatted<-as.numeric(HL60_20$AnalysisResultFormatted)
HL60_20$Visit <- factor(HL60_20$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))
```



```{r echo=FALSE,fig.height=5, fig.width=7.5}

summary_data <- tapply(HL60_20$AnalysisResultFormatted, list(tp=HL60_20$Visit,cohort = HL60_20$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data,
        main = "HL60 E:T 20:1",
        xaxt = "n",
        ylim=c(0,50),
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data),
        args.legend = list(x = "topright",
                           inset = c( .8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
axis(2, seq(0,50,5))
box(col="grey")
axis(1,at = c(2,7,13,18,23,28,33,38,43.5,48.1,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(5,10,15,20,25,30,35,40,45), col = "grey", lty = "dotted")
barplot(summary_data,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")

```



## HL60 E:T 6.6:1
```{r include=FALSE}
HL60_6<-subset(tike_data, Analyte=="I20/HL60 E:T 6.6:1"& (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_6$Visit<-as.factor(HL60_6$Visit)
HL60_6$Visit <- factor(HL60_6$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))
```



```{r echo=FALSE,fig.height=5, fig.width=7.5}
HL60_6$AnalysisResultFormatted<-as.numeric(HL60_6$AnalysisResultFormatted)
summary_data1 <- tapply(HL60_6$AnalysisResultFormatted, list(tp=HL60_6$Visit,cohort = HL60_6$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data1,
        main = "HL60 E:T 6.6:1",
        xaxt = "n",
        ylim=c(0,40),
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data1),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
axis(2, seq(0,41,5))
box(col="grey")
axis(1,at = c(2,7,13,18,23,28,33,38,44,48.5,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(5,10,15,20,25,30,35,40,45), col = "grey", lty = "dotted")
barplot(summary_data1,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data1),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")
```



## HL60 E:T 2.2:1
```{r include=FALSE}
HL60_2<-subset(tike_data, Analyte=="I20/HL60 E:T 2.2:1"& (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_2$Visit <- factor(HL60_2$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))

```

```{r echo=FALSE,fig.height=5, fig.width=7.5}

HL60_2$AnalysisResultFormatted<-as.numeric(HL60_2$AnalysisResultFormatted)
summary_data2 <- tapply(HL60_2$AnalysisResultFormatted, list(tp=HL60_2$Visit,cohort = HL60_2$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data2,
        main = "HL60 E:T 2.2:1",
        xaxt = "n",
        ylim=c(0,35),
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data2),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
axis(2, seq(0,50,5))
box(col="grey")
axis(1,at = c(2,7,13,18,23,28,33,38,44,48.5,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(5,10,15,20,25,30,35,40,45), col = "grey", lty = "dotted")
barplot(summary_data2,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data2),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")
```




## HL60+TriKE E:T 20:1
```{r include=FALSE}
HL60_trike_20<-subset(tike_data, Analyte=="I20/HL60/TriKE E:T 20:1"& (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_trike_20$Visit <- factor(HL60_trike_20$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))

```

```{r echo=FALSE,fig.height=5, fig.width=7.5}
HL60_trike_20$AnalysisResultFormatted<-as.numeric(HL60_trike_20$AnalysisResultFormatted)
summary_data3 <- tapply(HL60_trike_20$AnalysisResultFormatted, list(tp=HL60_trike_20$Visit,cohort = HL60_trike_20$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data3,
        main = "HL60+TriKE E:T 20:1",
        xaxt = "n",
        ylim=c(0,90),
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data3),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
axis(2, seq(0,90,5))
box(col="grey")
axis(1,at = c(2,7,13,18,23,28,33,38,43.3,48.1,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(10,20,30,40,50,60,70,80,90), col = "grey", lty = "dotted")
barplot(summary_data3,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data3),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")
```


## HL60+TriKE E:T 6.6:1
```{r include=FALSE}
HL60_trike_6<-subset(tike_data, Analyte=="I20/HL60/TriKE E:T 6.6:1"& (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_trike_6$Visit <- factor(HL60_trike_6$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))
```



```{r ,echo=FALSE ,fig.height=5, fig.width=7.5}
HL60_trike_6$AnalysisResultFormatted<-as.numeric(HL60_trike_6$AnalysisResultFormatted)
summary_data4 <- tapply(HL60_trike_6$AnalysisResultFormatted, list(tp=HL60_trike_6$Visit,cohort = HL60_trike_6$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data4,
        main = "HL60+TriKE E:T 6.6:1",
        ylim=c(0,90),
        xaxt = "n",
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data4),
        args.legend = list(x = "topright",
                           inset = c( .8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
box(col = "grey")
axis(2, seq(0,90,5))
axis(1,at = c(2,7,13,18,23,28,33,38,43.5,48,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(10,20,30,40,50,60,70,80,90), col = "grey", lty = "dotted")
barplot(summary_data4,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data4),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")
```



## HL60+TriKE E:T 2.2:1
```{r include=FALSE}
HL60_trike_2<-subset(tike_data, Analyte=="I20/HL60/TriKE E:T 2.2:1"& (Visit=='Day 1'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
HL60_trike_2$Visit <- factor(HL60_trike_2$Visit, levels = c("Day 1", "Day 8", "Day 15","Day 22"))
```

```{r echo=FALSE,fig.height=5, fig.width=7.5}
HL60_trike_2$AnalysisResultFormatted<-as.numeric(HL60_trike_2$AnalysisResultFormatted)
summary_data5 <- tapply(HL60_trike_2$AnalysisResultFormatted, list(tp=HL60_trike_2$Visit,cohort = HL60_trike_2$`Patient Number`),FUN = mean, na.rm = TRUE)

barplot(summary_data5,
        main = "HL60+TriKE E:T 2.2:1",
        xaxt = "n",
        ylim=c(0,80),
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data5),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE,xlab="Dose Levels (mcg/kg/day CIV)", ylab="Cytotoxicity (%)")
axis(2, seq(0,80,5))
box(col = "grey")
axis(1,at = c(2,7,13,18,23,28,33,38,43.5,48,53),labels = c("5","10","10","25","25","50","50","100","100","150","150"))

abline(h = c(10,20,30,40,50,60,70,80,90), col = "grey", lty = "dotted")
barplot(summary_data5,
        col = c("blue", "orange","grey", "yellow"),
        legend.text = rownames(summary_data5),
        args.legend = list(x = "topright",
                           inset = c( 0.8, 0)),
       beside = TRUE, axes=FALSE, add=TRUE,xaxt = "n")
```


# NK graphs


```{r include=FALSE}
new_variables<-c('Patient #',"Sequence Number", "Visit",  "Dose (mcg/kg/day CIV)","(NK) %CD16+")
nk_clean<-NK[new_variables]

nk_clean<-subset(nk_clean, (Visit=='Pre'|Visit=='Day 8'|Visit=='Day 15'|Visit=='Day 22'))
str(nk_clean)
nk_clean$Visit <- factor(nk_clean$Visit , levels=c( "Pre", "Day 8", "Day 15", "Day 22"))
nk_clean$`Patient #` <- factor(nk_clean$`Patient #` , levels=c( "Treated patient 1", "Treated patient 2", "Treated patient 3", "Treated patient 4","Treated patient 5","Treated patient 6","Treated patient 7","Treated patient 8","Treated patient 9","Treated patient 10","Treated patient 11","Treated patient 12"))

nk_clean$`Dose (mcg/kg/day CIV)` <- factor(nk_clean$`Dose (mcg/kg/day CIV)` , levels=c( "5 ug/kg", "10 ug/kg", "25 ug/kg", "50 ug/kg","100 ug/kg","150 ug/kg"))
nk_clean$Dose<-nk_clean$`Dose (mcg/kg/day CIV)`
```

# 12 paitents aggregated

```{r echo=FALSE}
plot(`(NK) %CD16+`~ Visit, data = nk_clean)
```
# Patients ploted individually, but color coded by dose.

```{r echo=FALSE}
ggplot(data=nk_clean, aes(x=Visit, y=`(NK) %CD16+`, group=`Patient #`))+
geom_line(aes(color=`Dose (mcg/kg/day CIV)`))+
geom_point(aes(color=`Dose (mcg/kg/day CIV)`))+
theme_hc()+
   ylim(40, 100)
```

# Data pooled together by dose

```{r include=FALSE}
library(kableExtra)
library(data.table)
library(Rmisc)
dose_g <- summarySE(nk_clean, measurevar="(NK) %CD16+", groupvars=c("Visit","Dose"))
dose_g

```

```{r echo=FALSE}
knitr::kable(dose_g, "pipe", caption = "TOP THREE DOSES POOLED BY DOSE", digits = 2)

```



```{r echo=FALSE}

ggplot(data=dose_g, aes(x=Visit, y=`(NK) %CD16+`, group=`Dose`))+
geom_line(aes(color=`Dose`))+
geom_point(aes(color=`Dose`))+
 theme_hc()+scale_colour_wsj("colors6")+
  ylim(60,100)
```

# TOP THREE DOSES:
## Pooled together by dose
```{r echo=FALSE}
nk_clean_top3<-subset(nk_clean, (Dose=='50 ug/kg'|Dose=='100 ug/kg'|Dose=='150 ug/kg'))
dose_g_top3 <- summarySE(nk_clean_top3, measurevar="(NK) %CD16+", groupvars=c("Visit","Dose"))

```

```{r echo=FALSE}
knitr::kable(dose_g_top3, "pipe", caption = "TOP THREE DOSES POOLED BY DOSE", digits = 2)
```

```{r echo=FALSE}
ggplot(data=nk_clean_top3, aes(x=Visit, y=`(NK) %CD16+`, group=`Patient #`))+
geom_line(aes(color=`Dose (mcg/kg/day CIV)`))+
geom_point(aes(color=`Dose (mcg/kg/day CIV)`))+
theme_hc()+
   ylim(40, 100)
```


## With Error Bars
```{r echo=FALSE}
ggplot(data=dose_g_top3, aes(x=Visit, y=`(NK) %CD16+`, group=`Dose`))+
geom_line(aes(color=`Dose`))+
geom_point(aes(color=`Dose`))+
   geom_errorbar(aes(ymin=`(NK) %CD16+`-se, ymax=`(NK) %CD16+`+se,color=`Dose`), width=.2,
                 position=position_dodge(0.05))+
theme_hc()+scale_colour_wsj("colors6")+
   ylim(40, 100)
```
## With No Error Bars
```{r echo=FALSE}
ggplot(data=dose_g_top3, aes(x=Visit, y=`(NK) %CD16+`, group=`Dose`))+
geom_line(aes(color=`Dose`))+
geom_point(aes(color=`Dose`))+
  theme_hc()+scale_colour_wsj("colors6")+ 
  ylim(60, 100)
```

